name: Automated Commit

on:
  push:
    branches: [master]
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_commit:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    
    env:
      TARGET_COMMITS_PER_DAY: 1000

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Gate Keeper - Check if it's time to commit
        id: gate_keeper
        run: |
          required_interval_seconds=$(( (24 * 3600) / ${{ env.TARGET_COMMITS_PER_DAY }} ))
          last_commit_time=$(git log --author="github-actions[bot]" --grep="\[skip ci\]" -1 --format=%ct || echo "0")
          current_time=$(date +%s)
          elapsed_time=$(( current_time - last_commit_time ))
          if (( elapsed_time >= required_interval_seconds )); then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and Push Commit
        if: steps.gate_keeper.outputs.should_run == 'true'
        run: |
          git config user.email "actions@github.com"
          git config user.name "github-actions[bot]"
          current_time_display=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Updated on $current_time_display" > TIMESTAMP.txt
          git add TIMESTAMP.txt
          commit_messages=("Update" "Refresh" "Renew" "Revise" "Sync" "Chore")
          random_msg=${commit_messages[$RANDOM % ${#commit_messages[@]}]}
          git commit -m "$random_msg TIMESTAMP.txt - $current_time_display" || echo "No changes to commit."
          git push
