name: Automated Commit

on:
  schedule:
    - cron: '* * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update_commit:
    runs-on: ubuntu-latest
    env:
      TARGET_COMMITS_PER_DAY: 1500

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Random Delay
        run: |
          interval=$((86400 / ${{ env.TARGET_COMMITS_PER_DAY }}))
          delay_seconds=$((RANDOM % (interval / 2) + (interval / 4)))
          sleep "${delay_seconds}s"

      - name: Update Timestamp
        run: |
          current_time=$(date '+%Y-%m-%d %H:%M:%S')
          echo "Updated on $current_time" > TIMESTAMP.txt

      - name: Setup Git
        run: |
          git config user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git config user.name "${{ github.repository_owner }}"

      - name: Commit
        run: |
          commit_messages=("Update" "Refresh" "Renew" "Revise")
          random_msg=${commit_messages[$RANDOM % ${#commit_messages[@]}]}
          git add TIMESTAMP.txt
          git commit -m "$random_msg - $(date '+%Y-%m-%d %H:%M:%S')"

      - name: Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          directory: '.'
          github_token: ${{ secrets.GITHUB_TOKEN }}
